version: '3'
services:
  php:
    image: php:8.2-fpm
    ports:
      - "9000:9000"
    volumes:
      - ${APP_DIR}:/var/www/html
    command: sh -c 
      "docker-php-ext-install pdo_mysql 
      && chown -R www-data:www-data /var/www
      && curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
      && composer install
      && php artisan migrate
      && php-fpm -F"
    depends_on:
      - memcache
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ${APP_DIR}:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - node
    command: nginx -g "daemon off;"

  node:
    image: node:16-alpine
    volumes:
      - ${APP_DIR}:/var/www/html
    ports:
      - "3000:3000"
    working_dir: /var/www/html
    command: sh -c "npm install -F && npm run dev"
    depends_on:
      - php

  memcache:
    image: memcached:alpine

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
